import Container from "@/components/Container";

export const metadata = {
  title: "Commission Disclosure | Zenvest Wealth",
  description: "Commission Disclosure for Zenvest Wealth"
};

const commissions = [
  { type: "Arbitrage Funds", y1: "0.05% to 0.60%", y2: "0.05% to 0.60%" },
  { type: "ELSS Funds", y1: "0.50% to 1.25%", y2: "0.50% to 1.25%" },
  { type: "Equity Oriented Funds", y1: "0.50% to 1.25%", y2: "0.50% to 1.25%" },
  { type: "Aggressive Hybrid Equity Funds", y1: "0.50% to 1.25%", y2: "0.50% to 1.25%" },
  { type: "Fixed Maturity Plans", y1: "0.05% to 0.50%", y2: "0.05% to 0.50%" },
  { type: "Fund of Funds", y1: "0.25% to 1%", y2: "0.25% to 1%" },
  { type: "Gilt Funds", y1: "0.25% to 1%", y2: "0.05% to 0.65%" },
  { type: "Hybrid Debt Funds", y1: "0.05% to 0.75%", y2: "0.05% to 0.75%" },
  { type: "Income Funds", y1: "0.05% to 1%", y2: "0.05% to 1%" },
  { type: "Index Funds", y1: "0.01% to 0.75%", y2: "0.01% to 0.75%" },
  { type: "Liquid Funds / Ultra Short-Term Funds", y1: "0.05% to 0.50%", y2: "0.05% to 0.50%" },
  { type: "Short-Term Income Funds", y1: "0.05% to 0.65%", y2: "0.05% to 0.65%" },
  { type: "Thematic / Sector Funds", y1: "0.50% to 1.25%", y2: "0.50% to 1.25%" }
];

export default function CommissionDisclosure() {
  return (
    <div className="pt-32 pb-24 bg-white min-h-screen">
      <Container className="max-w-5xl">
        <h1 className="text-4xl font-display font-bold text-navy-900 mb-8">Commission Disclosure</h1>
        
        <div className="bg-white rounded-xl shadow-sm border border-navy-100 p-8">
          <h2 className="text-xl font-bold text-navy-900 mb-2">Commission Disclosure under SEBI Circular SEBI/IMD/CIR No.4 /168230/09</h2>
          <p className="text-navy-600 mb-8 text-sm">The details of the commission earned by us from various Asset Management Companies (AMCs) are as below.</p>

          <div className="overflow-x-auto rounded-lg border border-navy-100 mb-8">
            <table className="w-full text-left text-sm">
              <thead className="bg-navy-900 text-white">
                <tr>
                  <th className="px-6 py-4 font-semibold whitespace-nowrap">Scheme Type</th>
                  <th className="px-6 py-4 font-semibold whitespace-nowrap">Trail 1st Year</th>
                  <th className="px-6 py-4 font-semibold whitespace-nowrap">Trail 2nd Year Onwards</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-navy-100 bg-white text-navy-800">
                {commissions.map((c, i) => (
                  <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-navy-50/50"}>
                    <td className="px-6 py-4 font-medium">{c.type}</td>
                    <td className="px-6 py-4">{c.y1}</td>
                    <td className="px-6 py-4">{c.y2}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p className="text-xs text-navy-600 leading-relaxed text-justify">
            *Investments in mutual funds are subject to market risk and customers should read the scheme-related documents / key information documents of the Mutual Fund products carefully before investing. This is on a best-effort basis and rates are updated as and when actual rates are received from AMCs. This is for information purposes only and does not represent any financial or other advice. The information contained in this presentation is general in nature. The client acknowledges that the prices and net asset values of the mutual fund schemes are subject to fluctuation based on the factors and the forces affecting the capital markets. Past performance of the sponsors, mutual funds, or their affiliates do not indicate or guarantee the future performance of any scheme in any manner, and historical performance, when presented, is purely for reference purposes. This page is an integral part of the document generated by us. Investment proposals are prepared on request of the client for general information and reference purposes. It aims to demonstrate a proposal considering the client's investment objective and investment preferences designed based on information provided by the client. The proposal is purely on a non-binding basis and the client is free to accept or reject the proposal. We shall not be held responsible for any direct or indirect loss caused by relying on this information. The client is free to seek the opinion of the legal, investment, and taxation expert for making investment decisions.
          </p>
        </div>
      </Container>
    </div>
  );
}
